import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from 'next/font/google'

export const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '500', '700'] // O '300' é o segredo para ser leve
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
